name: Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Echo current time
        run: timedatectl

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Hexo CLI
        run: npm install -g hexo-cli

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      
      - name: Generate pages
        run: hexo generate

      - name: Git config
        run: |
          git config --global user.name "LuckVd"
          git config --global user.email "VanDevon7478@gmail.com"
      - name: Deploy blog
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY"> ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone https://github.com/LuckVd/hexoCode.git
          cp -r ./public/* ./LuckVd.github.io/
          cd LuckVd.github.io
          git add .
          git commit -m "Github Action Automated Deployment $(date +'%Y-%m-%d %H:%M:%S')"
          git push "https://${GH_TOKEN}@github.com/LuckVd/LuckVd.github.io.git" main
